### ISSUE TITLE
Wrong QSPI flash size

### ISSUE THREAD

**Issue by dolence** [riverdi/riverdi-101-stm32h7-lvgl#1]
This:
`hqspi.Init.FlashSize = 27;`

Shouldn't be like this?
`hqspi.Init.FlashSize = 25;`

Since 2²⁶ = 67.108.864 (64 MB) and flashsize is defined as 2<sup>[flash size - 1]</sup>

Isn't the MT25QL512 flash size in 64 MB? Correct me if I'm wrong, but 27 isn't wrongly defining the flash size as 256 MB?

**Comment by lukasz-skalski** [comment]
Thanks for letting know - already fixed.
